### PR TITLE
Added Video Playback on Mac

### PR DESCRIPTION
**Pull request by ktabata**
Supported file format is `.mp4` files which contain `H.264` for video and `AAC` for audio.

@KyouBrayden Could you update the document? This feature will be released in 2.11.4.

### CODE REVIEW

**Comment by KyouBrayden** [comment]
Just to clarify, does Suika2 read the `.qt` extension for the QuickTime File Format alongside `.mov`?

**Comment by ktabata** [comment]
> Just to clarify, does Suika2 read the .qt extension for the QuickTime File Format alongside .mov?

I'm not sure, I'll give it a try.

**Comment by ktabata** [comment]
Confirmed!

* mov extension
    * H.264 ... OK
    * H.265 ... OK
* qt extension
    * H.264 ... OK
    * H.265 ... OK
* mp4 extension
    * H.264 ... OK
    * H.265 ... Partially OK (FourCC "hvc1" is ok, "hev1" is not ok.)

FourCC is too detailed, so shall we say we only support H.264?

**Comment by KyouBrayden** [comment]
> FourCC is too detailed, so shall we say we only support H.264?

I don't see any reason to keep `FourCC` as of now. Realistically it isn't going to be used, and if it is, it wouldn't be too common.

**Review by innocentvoice — APPROVED** [review]

**Pull request merged**
