### PR TITLE
ported to switch

### PR DESCRIPTION
**Pull request by YuriSizuku**
I make a port to switch. 
Now it support the Handheld game console mode.
I also write some document about how to use this port.

### CODE REVIEW

**Review by ktabata — APPROVED** [review]
LGTM. Thank you for your effort!

**Comment by ktabata** [comment]
For the sake of self-preservation, I hereby state that I do not have a developer's license for Switch myself, so I have no knowledge of the SDK that was used to create this code.
I have determined that this code does not infringe on Nintendo's intellectual property rights and will merge it.
In the unlikely event that there is a problem, I will treat it as an extension of the normal SDL2 code and remove the language regarding the `Switch`.
Please understand this in advance.

**Comment by 2439905184** [comment]
good

**Comment by minirop** [comment]
@ktabata it uses devkitpro, the community SDK, no copyright infringement here. Anyone can build it and run it in an emulator. (but you need a hacked console to run it on real hardware)

**Comment by ktabata** [comment]
Thank you for letting me know. That seems to be okay then.
Nintendo's legal department is scary, you know.

**Pull request merged**
